// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projectoefxs;

#nullable disable

namespace projectoefxs.Migrations
{
    [DbContext(typeof(RolesContext))]
    [Migration("20240305154137_InitialData")]
    partial class InitialData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("projectoefxs.Models.Rol", b =>
                {
                    b.Property<Guid>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrioridadRol")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RolId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Rol", (string)null);

                    b.HasData(
                        new
                        {
                            RolId = new Guid("b16a5720-10f6-4b9c-93df-298b4d543110"),
                            Apellido = "Martinez",
                            Cargo = "Ingeniero",
                            FechaCreacion = new DateTime(2024, 3, 5, 11, 41, 37, 223, DateTimeKind.Local).AddTicks(5780),
                            Nombre = "Jefferson",
                            PrioridadRol = 1,
                            Telefono = "04167170715",
                            UsuarioId = new Guid("b16a5720-10f6-4b9c-93df-298b4d5431ed")
                        },
                        new
                        {
                            RolId = new Guid("b16a5720-10f6-4b9c-93df-298b4d543120"),
                            Apellido = "Falcon",
                            Cargo = "Ingeniero junior pres",
                            FechaCreacion = new DateTime(2024, 3, 5, 11, 41, 37, 223, DateTimeKind.Local).AddTicks(5805),
                            Nombre = "Jonahtan",
                            PrioridadRol = 0,
                            Telefono = "04127171715",
                            UsuarioId = new Guid("b16a5720-10f6-4b9c-93df-298b4d543112")
                        });
                });

            modelBuilder.Entity("projectoefxs.Models.Usuario", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuario", (string)null);

                    b.HasData(
                        new
                        {
                            UsuarioId = new Guid("b16a5720-10f6-4b9c-93df-298b4d5431ed"),
                            Contraseña = "Dios123**@",
                            Correo = "jefferson123@gmail.com"
                        },
                        new
                        {
                            UsuarioId = new Guid("b16a5720-10f6-4b9c-93df-298b4d543112"),
                            Contraseña = "Dios123**@",
                            Correo = "jonatan@gmail.com"
                        });
                });

            modelBuilder.Entity("projectoefxs.Models.Rol", b =>
                {
                    b.HasOne("projectoefxs.Models.Usuario", "Usuario")
                        .WithMany("Rols")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("projectoefxs.Models.Usuario", b =>
                {
                    b.Navigation("Rols");
                });
#pragma warning restore 612, 618
        }
    }
}
